version: '3.8'
services:
  mq:
    image: ibmcom/mq:latest
    container_name: ibm-mq-container
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    ports:
      - "1414:1414"
      - "9443:9443"
    volumes:
      - ./mqdata:/mnt/mqm