version: '3'
services:
  ibm-mq:
    image: ibmcom/mq:latest
    container_name: ibm-mq-container
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_APP_USER=app
      - MQ_APP_PASSWORD=passw0rd
    ports:
      - "1414:1414"
      - "9443:9443"
    volumes:
      - ./mqdata:/var/mqm
volumes:
  mqdata:
